### ISSUE TITLE
Tutorial 2 missing

### ISSUE THREAD

**Issue by Dark-Touch** [PardCode/CPP-3D-Game-Tutorial-Series#2]
The files for tutorial 2 have been replaced with Tutorial 10 files.

**Comment by PardCode** [comment]
Hi, mate!
I'm sorry! I didn't see your message until now!
No problem! The source code for tutorial 2 hasn't been replaced! It has been only recommitted with another name!
I hope I've been helpful to you!

**Comment by Dark-Touch** [comment]
Well, unless you updated it since, the code is different than the one in your tutorial videos (There are lines that weren't added in the video). This is what prompted the confusion until I read the file names indicating it was meant for a different tutorial step. Great work by the way! Would love to keep learning as soon as the mixup is sorted out :)

**Comment by PardCode** [comment]
I'm sorry for that! 
Can you tell me, if you want, what are the files with the different lines of code respect the video tutorial? 
Anyway Thank you so much for your kind words and interest, mate!
