### ISSUE TITLE
i dont have win32 api

### ISSUE THREAD

**Issue by MaxGamer-max** [PardCode/CPP-3D-Game-Tutorial-Series#3]
how do i install it, i installed visual studio 2019 with almost nothing so its not heavy, what is the thing i have to check

**Comment by HTMLPuppy** [comment]
@MaxGamer-max what OS are you using?  I'm pretty sure that Win32 API only works with Windows, hence why the header file is `<windows.h>`

**Comment by MaxGamer-max** [comment]
win 7

**Comment by aceofjohnonline** [comment]
Then you must install c++ using the visual studio installer. You can Google how to do that. Then when you have c++ installed on visual studio you will have everything you need for these tutorials.

**Comment by MaxGamer-max** [comment]
ok thanks for telling me, i have changed to win 10 now but i dont know if
it was just the problem with not having c++ installed

**Comment by HTMLPuppy** [comment]
the link is also in every tutorial video
