### ISSUE TITLE
Unhandled exception thrown: read access violation. this->m_device_context was nullptr.

### ISSUE THREAD

**Issue by CyanakiBlizkana** [PardCode/CPP-3D-Game-Tutorial-Series#7]
Device Context.cpp 

#include "DeviceContext.h"
#include "SwapChain.h"

DeviceContext::DeviceContext(ID3D11DeviceContext* device_context):m_device_context(m_device_context)
{
}

bool DeviceContext::clearRenderTargetColor(SwapChain* swap_chain, float red, float green, float blue, float alpha)
{
	FLOAT clear_color[] = {red,green,blue,alpha};
	m_device_context->ClearRenderTargetView(swap_chain->m_rtv, clear_color); //The exception occurs right here 
	return true;
}

bool DeviceContext::release()
{
	m_device_context->Release();
	delete this;
	return true;
}

DeviceContext::~DeviceContext()
{
}

**Comment by CoderQCFromScraatch** [comment]
i have the same issue
